# This Ansible playbook adds a Slurm cluster for Open OnDemand (OOD) using a login node as a proxy for Slurm commands.

- name: Cluster config
  hosts: 127.0.0.1
  connection: local
  vars_files: vars.yml
  tasks:

    # Create the directory for cluster configuration files
    - name: Create cluster dir
      become: true
      ansible.builtin.file:
        path: /etc/ood/config/clusters.d
        state: directory

    # Copy wrapper scripts to the target directory
    - name: Copy wrapper scripts
      become: true
      ansible.builtin.copy:
        src: wrappers/
        dest: /usr/local/bin/{{ escaped_cluster_name }}_wrapper_scripts/
        mode: '0755'
  
    - name: Copy main slurm wrapper scripts to the target directory
      become: true
      template:
        src: 'slurm_proxy.j2'
        dest: '/usr/local/bin/{{ escaped_cluster_name }}_wrapper_scripts/slurm_proxy.sh'
        mode: '0755'

    # Write the cluster configuration file
    - name: Write clusterfile
      become: true
      template:
        src: 'slurm_cluster_definition.j2'
        dest: '/etc/ood/config/clusters.d/{{ escaped_cluster_name }}.yml'

    # Write the login node configuration file
    - name: Write login node cluster definition
      become: true
      template:
        src: 'login_cluster_definition.j2'
        dest: '/etc/ood/config/clusters.d/login_{{ escaped_cluster_name }}.yml'

    # set the /etc/ood/config/announcement.yml file to be dismisable
    - name: Set announcement file to be dismisable
      become: true
      lineinfile:
          state: present
          dest: /etc/ood/config/announcement.yml
          regexp: "^dismissible"
          line: 'dismissible: true'
