# This Ansible playbook sets up NFS mounts for Open OnDemand (OOD).
# Due to cyclecloud using /shared/home by default in a cluster and /home in a single VM
# The ansible has to mount over the standard home directory on the OOD machine.
# The cyclecloud user is only ever present in /home so it checks if it exists on /shared/home if not it makes it.
# This does cause an issue in the OOD portal job composer where a job exists on the cluster at /shared/home but on the OOD node it exists at /home.
# Jobs can still be submitted and monitored however the open job button will not be able to find /home/user on the cluster.

- name: NFS mounts setup
  hosts: 127.0.0.1
  connection: local
  vars_files: vars.yml
  tasks:

    # Mount the home directory from the NFS server
    - name: Initial mount of Home Dir
      become: true
      ansible.posix.mount:
        src: "{{ Home_mount_IP }}:{{ Home_mount_export }}"
        path: /shared/home
        state: mounted
        opts: "nofail"
        fstype: nfs

    # Check if the CycleCloud home directory exists
    - name: Check if CycleCloud home dir exists
      become: true
      ansible.builtin.stat:
        path: /shared/home/cyclecloud
      register: dircheck

    # Copy the CycleCloud home directory if it does not exist
    - name: Copy CycleCloud home dir if it does not exist
      become: true
      ansible.builtin.copy:
        src: /home/cyclecloud
        dest: /shared/home/
        remote_src: true
        owner: cyclecloud
        group: cyclecloud
        mode: preserve
      when: dircheck.stat.isdir is not defined and not dircheck.stat.exists

    # Bind mount /shared/home to /home
    - name: Bind /shared/home to /home
      become: true
      ansible.posix.mount:
        path: /home
        src: /shared/home
        opts: "bind, nofail"
        state: mounted
        fstype: none
